source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.7.1'

gem 'thor'
gem 'colorize'
gem 'rouge'
gem 'rake'
gem 'httparty'
gem 'dotenv'
gem 'tty-command'
gem 'tty-markdown'
gem 'tty-table'
gem 'tty-box'
gem 'tty-prompt'
gem 'hashie'
gem 'pry'
gem 'subprocess'
gem 'ncumbra'
# gem 'curses'
