#!/usr/bin/env ruby
require 'rubygems'
require 'bundler'
Bundler.require(:default)

module App
  class SubCommandBase < Thor
    def self.banner(command, namespace = nil, subcommand = false)
      "#{basename} #{subcommand_prefix} #{command.usage}"
    end

    def self.subcommand_prefix
      self.name.gsub(%r{.*::}, '').gsub(%r{^[A-Z]}) { |match| match[0].downcase }.gsub(%r{[A-Z]}) { |match| "-#{match[0].downcase}" }
    end
  end

  class CLI < Thor
    Dir["./tasks/**/*.rb"].each {|file| require file }
    App.constants.select {|c| (App.const_get(c).is_a? Class) && (App.const_get(c.to_s).superclass.to_s == "App::SubCommandBase")}.each do |klass|
      desc klass.to_s, "Use vlab #{klass} for more information"
      subcommand "#{klass.to_s}", Kernel.const_get("App::#{klass.to_s}")
    end
  end
end

App::CLI.start
