name: github pages

on:
  pull_request:
    paths:
      - '.github/workflows/05-gh-pages-publish.yml'
      - 'website/**'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/05-gh-pages-publish.yml'
      - 'website/**'

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: '12.x'
      - name: Run Playbook Config
        run: |
          date +%s | sha256sum | base64 | head -c 32  > ~/.vlab_vault_pass
          mkdir -p settings_ci
          echo "PASSWORDLESS_SSHKEY=''" > tasks/ansible_bash.vars
          ansible-playbook -i inventory playbook.ci_config.yml
      - name: Run Playbook
        run: ansible-playbook --extra-vars="@settings_ci/config.yml" -i inventory playbook.ci.yml
      - name: Test Build
        run: |
          yarn install --frozen-lockfile
          npm run build
        working-directory: website
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.3.0
        with:
          node-version: '12.x'
      - name: Run Playbook Config
        run: |
          date +%s | sha256sum | base64 | head -c 32  > ~/.vlab_vault_pass
          mkdir -p settings_ci
          echo "PASSWORDLESS_SSHKEY=''" > tasks/ansible_bash.vars
          ansible-playbook -i inventory playbook.ci_config.yml
      - name: Run Playbook
        run: ansible-playbook --extra-vars="@settings_ci/config.yml" -i inventory playbook.ci.yml
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
        working-directory: website
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-
      - run: yarn install --frozen-lockfile
        working-directory: website
      - run: yarn build
        working-directory: website
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
